version: 2
updates:
  # Maintain dependencies for Dart/Flutter (pub)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10

  # Maintain dependencies for Android (Gradle)
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5

